### ISSUE TITLE
受你这个启发

### ISSUE THREAD

**Issue by qingfeng** [tonicbupt/commitlog#8]
我觉得我应该写一个提交commit log的时候，自动追加当前btc的价格

**Comment by qingfeng** [comment]
@gitthanks thanks @tonicbupt 1 AVH

**Comment by gitthanks** [comment]
@qingfeng, you have bonus 1 AVH to @tonicbupt. @tonicbupt is still not the member of [gitthanks.com](https://gitthanks.com), login using github and withdraw bonus to [Bixin Crypto Wallet](https://bixin.im)

**Comment by tonicmuroq** [comment]
🍻 这个就厉害了!

**Comment by gitthanks** [comment]
@qingfeng, AVH balance insufficient. Please login at [gitthanks.com](https://gitthanks.com) and deposit using [Bixin Crypto Wallet](https://bixin.im)
